#ifndef I3D_ASTEROIDCONSTANTS_H
#define I3D_ASTEROIDCONSTANTS_H

float constexpr ASTEROID_MIN_SPEED = 150;
float constexpr ASTEROID_MAX_SPEED = 300;

float constexpr ASTEROID_MIN_ROTATION_SPEED = 50;
float constexpr ASTEROID_MAX_ROTATION_SPEED = 100;

float constexpr ASTEROID_MIN_RADIUS = 90;
float constexpr ASTEROID_MAX_RADIUS = 180;

int constexpr ASTEROID_MIN_HEALTH = 20;
int constexpr ASTEROID_MAX_HEALTH = 40;

float constexpr ASTEROID_STACK_COUNT = 30;
float constexpr ASTEROID_SECTOR_COUNT = 30;

#endif // I3D_ASTEROIDCONTANTS_H