#ifndef I3D_ASTEROIDCONSTANTS_H
#define I3D_ASTEROIDCONSTANTS_H

float constexpr ASTEROID_MIN_RADIUS = 10;
float constexpr ASTEROID_MAX_RADIUS = 10;

float constexpr ASTEROID_STACK_COUNT = 20;
float constexpr ASTEROID_SECTOR_COUNT = 20;

float constexpr ASTEROID_MIN_SPEED = 20;
float constexpr ASTEROID_MAX_SPEED = 50;

#endif // I3D_ASTEROIDCONTANTS_H